#!/bin/bash

LOG_FILE="/var/log/aptupdate.log"

check() {
    if [ $1 -eq 0 ]; then
        echo -e "\e[32mSUCCESS\e[0m"
    else
        echo -e "\e[31mFAILED\e[0m"
    fi
}

NULLIFY="/dev/null"

echo "Updating package index..."
sudo apt update -y &>>$LOG_FILE
check $?

echo "Upgrading package apt..."
sudo apt upgrade -y &>>$LOG_FILE
check $?

echo "Updating ubuntu-advantage-tools..."
sudo apt install ubuntu-advantage-tools -y &>>$LOG_FILE
check $?

sudo apt update &>>$LOG_FILE
check $?

# Perform distribution upgrade
echo "Performing distribution upgrade..."
sudo apt-get clean &>>$LOG_FILE
check $?

sudo apt-get autoremove -y &>>$LOG_FILE
check $?

sudo apt autoremove --purge -y &>>$LOG_FILE
check $?

sudo apt autoclean &>>$LOG_FILE
check $?

# Prevent interactive prompts
export DEBIAN_FRONTEND=noninteractive
sudo apt dist-upgrade -y &>>$LOG_FILE
check $?

# Install unattended-upgrades package
echo "Installing unattended-upgrades..."
sudo apt install unattended-upgrades -y &>>$LOG_FILE
check $?

# Reconfigure unattended-upgrades with low priority attended upgrade
echo "Reconfiguring unattended-upgrades..."
sudo dpkg --configure -a  &>>$LOG_FILE
check $?

sudo dpkg-reconfigure --priority=low unattended-upgrades &>>$LOG_FILE
check $?

sudo rm -rf /var/tmp/*    
sudo apt-get clean    &>>$LOG_FILE 
sudo apt-get autoremove &>>$LOG_FILE
check $?

# Check if ClamAV is installed
if ! command -v freshclam &>/dev/null; then
    echo "ClamAV (freshclam) is not installed. Please install it first."
    exit 1
fi

# Update ClamAV virus definitions
echo "Checking and updating ClamAV virus definitions..."
update_output=$(sudo freshclam 2>&1)

if [ $? -eq 0 ]; then
    echo "ClamAV virus definitions are up to date."
else
    echo "Error updating ClamAV definitions:"
    echo "$update_output"
    exit 1
fi

# Display ClamAV database version
clam_version=$(sudo clamscan --version | grep 'ClamAV' | awk '{print $2}')
if [ -n "$clam_version" ]; then
    echo "ClamAV Version: $clam_version"
else
    echo "Unable to retrieve ClamAV version."
fi

sudo rm -rf /var/lib/snapd/cache/* &>>$LOG_FILE

echo "All steps completed."
exit 0
