#!/bin/bash

sudo docker container prune -f

sudo docker rm -f $(sudo docker ps -aq)

sudo docker rmi -f $(sudo docker images -q)


sudo docker volume rm $(sudo docker volume ls -q)

sudo docker network prune -f

sudo docker builder prune -a -f

sudo docker system prune -a -f --volumes

sudo docker system df
