#!/bin/bash
# instal gitlab community edition on server

sudo apt-get update
sudo apt-get install -y curl openssh-server ca-certificates tzdata perl


 sudo apt-get install -y postfix

  curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash